// <auto-generated />
using System;
using ApiRemoteWorkClientBlockChain.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ApiRemoteWorkClientBlockChain.Migrations
{
    [DbContext(typeof(RemoteWorkClientDbContext))]
    [Migration("20250522040059_InitDb")]
    partial class InitDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LibRemoteAndClient.Entities.Remote.Client.GuidTokenAuth", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("GuidTokenGlobal")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("nonce_used_auth", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
