// <auto-generated />
using System;
using ApiRemoteWorkClientBlockChain.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ApiRemoteWorkClientBlockChain.Migrations
{
    [DbContext(typeof(RemoteWorkClientDbContext))]
    partial class RemoteWorkClientDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LibEntitiesRemote.Entities.Client.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AttemptsConnection")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("DateConnected")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("IpLocal")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("Port")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<DateTimeOffset>("PrimaryConnection")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("StateClient")
                        .HasColumnType("integer");

                    b.Property<int?>("TimeoutReceive")
                        .HasMaxLength(8)
                        .HasColumnType("integer");

                    b.Property<int?>("TimeoutSend")
                        .HasMaxLength(8)
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("client_primary_contact_server", (string)null);
                });

            modelBuilder.Entity("LibRemoteAndClient.Entities.Remote.Client.GuidTokenAuth", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("GuidTokenGlobal")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("nonce_used_auth", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
